language: elixir
sudo: false

branches:
  only:
    - master
    - development

elixir:
  - 1.5.1
  - 1.5.2
  - 1.5.3
otp_release:
  - 20.0
  - 20.1
  - 20.2

matrix:
  include:
    - elixir: 1.4.0
      otp_release: 19.1
    - elixir: 1.4.4
      otp_release: 19.1
    - elixir: 1.4.4
      otp_release: 19.2
