name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        include:
          - pair:
            otp: 21.3
            elixir: 1.10.0
          - pair:
            otp: 21.3
            elixir: 1.10.3
          - pair:
            otp: 21.3
            elixir: 1.11.1
          - pair:
            otp: 21.3
            elixir: 1.11.2
          - pair:
            otp: 21.3
            elixir: 1.11.3
          - pair:
            otp: 22.2
            elixir: 1.10.0
          - pair:
            otp: 22.2
            elixir: 1.10.3
          - pair:
            otp: 22.2
            elixir: 1.11.1
          - pair:
            otp: 22.2
            elixir: 1.11.2
          - pair:
            otp: 22.2
            elixir: 1.11.3
          - pair:
            otp: 22.2
            elixir: 1.12.0
          - pair:
            otp: 22.2
            elixir: 1.12.1
          - pair:
            otp: 23.0
            elixir: 1.10.0
          - pair:
            otp: 23.0
            elixir: 1.10.3
          - pair:
            otp: 23.0
            elixir: 1.11.1
          - pair:
            otp: 23.0
            elixir: 1.11.2
          - pair:
            otp: 23.0
            elixir: 1.11.3
          - pair:
            otp: 23.0
            elixir: 1.12.0
          - pair:
            otp: 23.0
            elixir: 1.12.1
          - pair:
            otp: 23.2
            elixir: 1.10.0
          - pair:
            otp: 23.2
            elixir: 1.10.3
          - pair:
            otp: 23.2
            elixir: 1.11.1
          - pair:
            otp: 23.2
            elixir: 1.11.2
          - pair:
            otp: 23.2
            elixir: 1.11.3
          - pair:
            otp: 23.2
            elixir: 1.12.0
          - pair:
            otp: 23.2
            elixir: 1.12.1
          - pair:
            otp: 24.0
            elixir: 1.10.0
          - pair:
            otp: 24.0
            elixir: 1.10.3
          - pair:
            otp: 24.0
            elixir: 1.11.1
          - pair:
            otp: 24.0
            elixir: 1.11.2
          - pair:
            otp: 24.0
            elixir: 1.11.3
          - pair:
            otp: 24.0
            elixir: 1.12.0
          - pair:
            otp: 24.0
            elixir: 1.12.1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix test
