name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  mix_test:
    name: mix test (Erlang/OTP ${{matrix.otp}} | Elixir ${{matrix.elixir}})
    strategy:
      fail-fast: false
      matrix:
        include:
          - otp: 21.3.8.16
            elixir: 1.10.0
          - otp: 23.0.2
            elixir: 1.10.0
          - otp: 21.3.8.16
            elixir: 1.10.3
          - otp: 23.0.2
            elixir: 1.10.3
          - otp: 21.3.8.16
            elixir: 1.11.2
          - otp: 23.0.2
            elixir: 1.11.2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-elixir@v1.4.2
        with:
          otp-version: '${{matrix.otp}}'
          elixir-version: '${{matrix.elixir}}'
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Run Tests
        run: mix test
